davidcelis/api-pagination

- .gitignore
- api-pagination.gemspec
- lib/grape/pagination.rb
This pull request enables support for Grape 0.10 since they refactored the way settings are set and retrieved.  Also added Appraisals gem to test both versions locally and on travis-CI.  
If you can find a prettier way of dealing with this please comment or update.
Can run specs against Grape 0.10 and 0.9 with: 
bundle exec appraisal rspec spec
> support for Grape 0.10 with refactored settings

- README.md
- lib/api-pagination.rb
- lib/grape/pagination.rb
- lib/rails/pagination.rb
- spec/grape_spec.rb
- spec/rails_spec.rb
- not always we want to have the Total and Per-Page headers with that
name, we may want to have a custom one like: X-Total-Count or
X-Per-Page.
- if nothing is configured it defaults to Total and Per-Page as the gem
already did.
Merged with the other pull requests that caused conflicts.
> Allowing to configure custom headers for Total and Per-Page

- lib/api-pagination/configuration.rb
This PR defers warnings to the first time ApiPagination.configuration.paginator is called.
This way no warnings will be generated if someone has explicitly defined a paginator even though more than one might be present.
> Remove warnings if user has explicitly defined paginator

- lib/grape/pagination.rb
- spec/grape_spec.rb
Hi there,
we have api with resource which can be in multiple states. We want to filter by that state.
When we try to filter by multiple states at once we get back invalid pagination links
request url:
http://api.com/api/v1/resource?page=1&state%5B%5D=new&state%5B%5D=active
decoded query string = "?page=1&state[]=active&state[]=new"
returned link:
<http://api.com/api/v1/resource?page=30&**state%5B%5D%5B%5D=new&state%5B%5D%5B%5D=active**>; rel="last"
decoded query string = "?page=1&**state[][]=active&state[][]=new**"
The problem is in parsing old parameters as you can see in commit. For parsing array arguments with brackets `Rack::Utils.parse_nested_query` must be used.
Note:
Since we are in rails land mostly i assume we want to use array query parameters with square brackets. It is what …
> Return array query parameters same as received

- lib/api-pagination.rb
- spec/api-pagination_spec.rb
When collection is an array, we want to pass options which like `total_count: 999` to paginate_array.
So, 
```ruby
paginate  (1..999).to_a, 
page: 20, 
per_page: 50, 
paginate_array_options: { 
total_count: 999, 
offset: 9
}
```
> Keep former behaviour for Kaminari.paginate_array

- README.md
- lib/api-pagination/configuration.rb
- lib/grape/pagination.rb
- lib/rails/pagination.rb
- spec/grape_spec.rb
- spec/rails_spec.rb
Hi,
I wanted to use api-pagination on my API and https://github.com/DanielBlanco/her-kaminari on the project using the API, but the header giving the information about the requested page was missing.
I couldn't find a reference about a W3C spec for this, so I made it optional (to be used with X-Page for example)
> Add page header

- .gitignore
- README.md
- lib/api-pagination/configuration.rb
- lib/grape/pagination.rb
- lib/rails/pagination.rb
- spec/rails_spec.rb
- spec/support/numbers_controller.rb
**api-pagination** uses `params[:page]` and `params[:per_page]` to set the current page and per-page options in the controller by default. This commit allows user to actually override those and use their own getters or specify the name of the parameter. So they can use for example `params[:page][:number]` for current page by default.
No breaking changes (just one more feature)
> Add support for optional param names

- lib/api-pagination.rb
- spec/rails_spec.rb
Both kaminari and will_paginate support `per_page` configuration on the model:
```
class User < ActiveRecord::Base
paginates_per 50
end
```
```
class User < ActiveRecord::Base
self.per_page = 50
end
```
This PR is adding a functionality to `api-pagination` to use the values from model by default, so the `per_page` doesn't have to be same for all resources or overridden in controller.
```
def index
@users = User.all
paginate @users # per_page will be 50
end
```
Fixes #48
> Fetch per_page from model by default

- README.md
I tried and found that `api-pagination` v3.1.0+ does not work with `grape` v0.9.0 or earlier.
> Fix version number of api-pagination for grape in README

- .travis.yml
- spec/spec_helper.rb
Following the discussion in #55, since it hadn't been touched in months, I implemented the suggested solution so I could get my local specs passing.
> Set default paginator in ENV so specs don't fail without it

- lib/rails/pagination.rb
- spec/rails_spec.rb
- spec/support/numbers_controller.rb
The PR allow to specify total count of paginated array when kaminari used as a paginator. See more [here](https://github.com/amatsuda/kaminari#paginating-a-generic-array-object). 
The PR similar to https://github.com/davidcelis/api-pagination/pull/50, but in addition has test coverage.
> Take total_count option when kaminari used

- lib/api-pagination/hooks.rb
- lib/api-pagination/version.rb
- spec/rails_spec.rb
- spec/support/numbers_controller.rb
In Rails 5:
* The parent controller for the API is `ActionController::API` not `ActionController::Base`
* When extending the ActionController it needs to be nested in `ActiveSupport.on_load`
> Add Rails 5 support

- lib/api-pagination/hooks.rb
Fix for Rails < v5 and rails-api gem.
> Restore support for Rails 4.x using rails-api

- lib/rails/pagination.rb
- spec/rails_spec.rb
Encountered an error within `Rack::Handler::Webrick`. Apparently that handler (which would be default for many stock rails installations in development) wants to make sure that the contents of each value in the headers hash is not multiline, and assumes that the value of each header is a string. The other values we set for headers are coerced to string, but not `Total`. So we need to make sure it's a string for compatibility with downstream handlers.
The error `Undefined method "split" for 23:fixnum` was coming up if i supplied `total_count` to `paginate_array_options` as an integer. When I tried supplying a string, then the call to `Kaminari.paginate_array` would fail as Kaminari expects an integer value.
You can see where this error was coming up in the following capture. 
```
From: …
```
> Total count header plays nice with Rack::Handler::Webrick

- README.md
clicked the link to `rails-api/active_model_serializers` and noticed it was broken - just a quick fix to the correct url (the second underscore was a dash instead by mistake).
> Fix typo in link to active_model_serializers

- lib/api-pagination.rb
- spec/api-pagination_spec.rb
New kaminari 1.0's `last_page?` method behavior is changed: now it returns false if current page is bigger then total pages.
This breaks our API: `Link` header with `next` and `last` urls appears even on the empty collection (because `current_page` is always 1 and `total_pages` is always 0).
This pull-request adds work-around keeping in mind that WillPaginate does not have `#out_of_range?` method.
> Kaminari 1.0 last_page? behavior fix

- lib/api-pagination.rb
- spec/api-pagination_spec.rb
ApiPagination#paginate takes `options`. These options are then part of paginating the collection using the WillPaginate::Collection#paginate method. Only `page` and `per_page` used to be passed through all the way down to the will_paginate method. This PR makes sure that we simply pass through all options passed in. 
This specifically adds support for a total_entries size different from the size of the collection.
> Adding will_paginate support for total_entries being passed in as an option

- lib/api-pagination.rb
Remove the extra db query for ActiveRecord::Associations::CollectionProxy and ActiveRecord::Relation
Right now, to check the default per page count, it uses collection.first.class to get the model class. This will cause an extra db request. It's better to remove that. And in test, it use an array of integers as the collection. So I check if the collection respond_to :table_name method first to decide which way to use to get the model class.
> remove the extra db query 

- lib/api-pagination.rb
Fix for issue #83 
Use classify instead of `singularize.capitalize` to work in all cases.
> Fix regression for multi word classes

- lib/api-pagination/configuration.rb
- lib/rails/pagination.rb
- spec/rails_spec.rb
It can be useful to configure a hardcoded base url to be used in the headers of api pagination. 
In case the application is reachable at multiple urls and caching is used, all users get will receive the header with the hostname that was used in the first request. 
This can be undesireable because the application might not be reachable for everyone under that hostname.
> add config option for base_url

- README.md
- lib/grape/pagination.rb
- spec/grape_spec.rb
- spec/support/numbers_api.rb
If a max_per_page value is added to grape then it is show in the docs.
This avoids confusing if someone tries to pass in a value greater than
max_per_page as it will return an error so the user can correct
themself. Note this may be a breaking change for some people.
> Add max_per_page value to grape swagger docs

- lib/api-pagination.rb
This PR should fix error `NameError: uninitialized constant Pagy` when using this gem without pagy gem installed.
> Fix "NameError: uninitialized constant Pagy" when pagy gem is not installed

- README.md
- lib/api-pagination.rb
- spec/api-pagination_spec.rb
- spec/grape_spec.rb
- spec/rails_spec.rb
- spec/support/shared_examples/first_page.rb
- spec/support/shared_examples/last_page.rb
When you set the `include_total` option to false, the total number of records is still needed for the last link header. This pr 'fixes' that by not including the last link header when you disable the `include_total` option. When using Kaminari, this prevents the `count` call which can speed up the pagination process by a lot when using big datasets.
In addition I found that when you write the test
```ruby
expect(links).not_to include('rel="prev"')
```
that it check if that string has an exact match to the links **array**. This will thus always be false! Therefore I added the `link` helper which is just the raw header and use that in the specs so it makes a string comparison. 
This pr Closes #85
> Remove last link header when include total option is false

- lib/api-pagination.rb
One might want to override the total given in the headers.
It is already possible with will_paginate and kaminari, I modificated the function for pagy in order to have the same possibility.
> [BugFix Issue #106] authorize to override count using pagy

- api-pagination.gemspec
- lib/api-pagination.rb
- spec/active_record_spec.rb
- spec/rails_spec.rb
- spec/support/active_record/foo.rb
- spec/support/active_record/schema.rb
It appears that this library services ActiveRecord primarily, so I wanted to use `#klass` instead of reifying it from the table name because it broke for me earlier in the following situation: 
- Table named `diy_links`.
- Model named `DIYLink`.
- Method attempts to reify `DiyLink` and fails.
I will add a spec later today, hope this is helpful! 👍
> Better behavior for #detect_model

- lib/api-pagination/hooks.rb
- spec/grape_spec.rb
Fixes the ``undefined method `paginate` for #<Class>``, due to the [recent (internal) changes in `Grape 1.2`](https://github.com/ruby-grape/grape/blob/v1.2.0/UPGRADING.md#upgrading-to--120):
```
Exiting
/usr/src/app/app/controllers/api/something.rb:25:in `block (3 levels) in <class:Something>': undefined local variable or method `paginate' for #<Class:0x00005648e45f79f8> (NameError)
from /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:88:in `instance_eval'
from /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:88:in `block in nest'
from /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:88:in `each'
from /usr/local/bundle/gems/grape-1.2.2/lib/grape/api/instance.rb:88:in `nest'
from /usr/local/bundle/gems/grape-1.2.2/lib/grape/dsl/routing.rb:168:in `block …
```
> Add compatibility with Grape >= 1.2.0
